name: build-conda
on:
  workflow_dispatch:
jobs:
  build-conda:
    runs-on: ubuntu-latest
    image:
      quay.io/condaforge/linux-anvil-x86_64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build conda package
        uses: prefix-dev/rattler-build-action@v0.2.23
        with:
          recipe-path: recipe.yaml
